[webservers]
web-1 ansible_host=93.77.181.112 fqdn=web-1.ru-central1.internal
web-2 ansible_host=158.160.56.198 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=89.169.152.236 fqdn=main.ru-central1.internal
replica ansible_host=158.160.38.96 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=158.160.60.217 fqdn=fhm3mnlt6oh82v3o39gj.auto.internal
